### PR TITLE
imageName added to SubmitContainerTokenRequest

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will add imageName to SubmitContainerTokenRequest

### CODE REVIEW

**Comment by munishchouhan** [comment]
@marcodelapierre @pditommaso please review

**Review by marcodelapierre — APPROVED** [review]
looks good - thanks Munish

**Comment by marcodelapierre** [comment]
@pditommaso I think this can be merged

**Comment by marcodelapierre** [comment]
@pditommaso I can merge if OK with you

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
