### PR TITLE
Improve container credentials retrieval using workflow compute environment

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will add support to retrieve credentials for workflow compute
Related to https://github.com/seqeralabs/wave/issues/223

### CODE REVIEW

**Comment by munishchouhan** [comment]
@pditommaso please release wave-api new version

**Comment by munishchouhan** [comment]
sorry, I don't understand
the tests in this PR https://github.com/seqeralabs/wave/pull/303 are failing
because the current WAVE-API doesn't contain `towerWorkflowId`
so to make the tests pass, I need a new version
or should I make an RC release?

**Comment by pditommaso** [comment]
Fair enough https://github.com/seqeralabs/libseqera/commit/6ef7e242647e385b0dfd24cd53b1e0021b7f496b 

Tho, you should be able to test it locally using `includeBuild`

**Comment by munishchouhan** [comment]
I already tested it locally with this PR

**Pull request merged**
