### PR TITLE
2 remove runcript from singularity build

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will remove %runscript from singularity image and make it simple

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]
leave to @marcodelapierre to confirm

**Comment by pditommaso** [comment]
Working in my tests, leave Marco propose any change post-merging

**Review by marcodelapierre — COMMENTED** [review]
Changes look good, two important comments, especially the first one:

1. If still as is, I strongly recommend using `singularity exec` instead of `singularity run`, as this is the correct, supported usage for Singularity (see singularity docs, https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#executing-commands vs https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#running-a-container

2. The image hash for singularity vs docker is different, right?

**Comment by pditommaso** [comment]
> The image hash for singularity vs docker is different, right?

yes 

> If still as is, I strongly recommend using singularity exec instead of singularity run

The rationale was to align to the Docker entrypoint behaviour, especially for the problem of Conda initialization. See [here](https://github.com/mamba-org/micromamba-docker/issues/155#issuecomment-1684890431). However, I understand that also `run` can have negative side effects. Let's discussion on [nextflow](https://github.com/nextflow-io/nextflow) repo

**Comment by marcodelapierre** [comment]
Hi @pditommaso  have a look at this comment of mine:

https://github.com/seqeralabs/wave/pull/288#issuecomment-1709849153.

Although I need to have a closer look at the scripts/requirements for https://github.com/mamba-org/micromamba-docker/issues/155#issuecomment-1684890431, I am pretty sure that the `/.singularity.d/env/` approach would fix `singularity exec` and `singularity shell`, including that case.

It looks to me like right now Nextflow is still using `exec`, right? See https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy#L63

So please let me know how you would best like to follow up on this, based on the extra info above.

**Comment by marcodelapierre** [comment]
Thanks for sharing these code refs Paolo 👍

**Pull request merged**
